# Generated by Django 5.2.7 on 2025-11-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Rótulo do Botão')),
                ('url', models.CharField(help_text='Ex: /gerencia/passeios/passeio/add/ ou admin:passeios_passeio_add', max_length=200, verbose_name='URL ou Nome da Rota')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Números menores aparecem primeiro.', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar este botão do dashboard.', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Ação Rápida',
                'verbose_name_plural': 'Ações Rápidas',
                'ordering': ['ordem'],
            },
        ),
    ]
