# Generated by Django 5.2.7 on 2025-11-01 14:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Destino')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(default='fa-solid fa-map-location-dot', max_length=50, verbose_name='Ícone (Font Awesome)')),
            ],
            options={
                'verbose_name': 'Categoria de Pacote',
                'verbose_name_plural': 'Categorias de Pacotes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Pacote')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(max_length=300, verbose_name='Descrição Curta')),
                ('description', models.TextField(verbose_name='Descrição Completa')),
                ('highlights', models.TextField(help_text='Principais pontos turísticos e atrações', verbose_name='Destaques do Pacote')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Original')),
                ('discount_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto (%)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duração (dias)')),
                ('duration_nights', models.PositiveIntegerField(default=0, verbose_name='Duração (noites)')),
                ('max_people', models.PositiveIntegerField(default=20, verbose_name='Máximo de Pessoas')),
                ('min_people', models.PositiveIntegerField(default=2, verbose_name='Mínimo de Pessoas')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('moderate', 'Moderado'), ('challenging', 'Desafiador')], default='easy', max_length=20, verbose_name='Dificuldade')),
                ('includes', models.TextField(help_text='Liste tudo que está incluído no pacote', verbose_name='O que está incluso')),
                ('excludes', models.TextField(blank=True, help_text='Liste o que não está incluído', verbose_name='O que não está incluso')),
                ('available_from', models.DateField(verbose_name='Disponível a partir de')),
                ('available_until', models.DateField(verbose_name='Disponível até')),
                ('featured_image', models.ImageField(upload_to='packages/featured/', verbose_name='Imagem Principal')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='packages/gallery/', verbose_name='Galeria 1')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='packages/gallery/', verbose_name='Galeria 2')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='packages/gallery/', verbose_name='Galeria 3')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('sold_out', 'Esgotado')], default='active', max_length=20, verbose_name='Status')),
                ('featured', models.BooleanField(default=False, verbose_name='Pacote em Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagecategory', verbose_name='Categoria')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.destination', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Pacote Turístico',
                'verbose_name_plural': 'Pacotes Turísticos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages.tourpackage', verbose_name='Pacote')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('preferred_date', models.DateField(verbose_name='Data Preferida')),
                ('number_of_people', models.PositiveIntegerField(verbose_name='Número de Pessoas')),
                ('special_requests', models.TextField(blank=True, verbose_name='Solicitações Especiais')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('contacted', 'Contatado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.tourpackage', verbose_name='Pacote')),
            ],
            options={
                'verbose_name': 'Solicitação de Reserva',
                'verbose_name_plural': 'Solicitações de Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
