# Generated by Django 5.2.7 on 2025-11-01 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado/Província')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='destinations/', verbose_name='Imagem Principal')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Amigável')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourPackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Amigável')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria de Pacote',
                'verbose_name_plural': 'Categorias de Pacotes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Amigável')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descrição Curta')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duração (dias)')),
                ('duration_nights', models.PositiveIntegerField(verbose_name='Duração (noites)')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Máximo de Participantes')),
                ('min_participants', models.PositiveIntegerField(default=2, verbose_name='Mínimo de Participantes')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil'), ('expert', 'Expert')], default='easy', max_length=10, verbose_name='Dificuldade')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço por Pessoa')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('available_spots', models.PositiveIntegerField(default=0, verbose_name='Vagas Disponíveis')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('booking_deadline', models.DateField(blank=True, null=True, verbose_name='Prazo para Reserva')),
                ('includes', models.TextField(blank=True, verbose_name='O que está incluído')),
                ('excludes', models.TextField(blank=True, verbose_name='O que não está incluído')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='Imagem Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination', verbose_name='Destino')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tourpackagecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Pacote Turístico',
                'verbose_name_plural': 'Pacotes Turísticos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID do Pedido')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('customer_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('customer_address', models.TextField(blank=True, verbose_name='Endereço')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Pessoas')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto Aplicado')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('pix', 'PIX'), ('bank_transfer', 'Transferência Bancária'), ('installments', 'Parcelamento')], max_length=20, verbose_name='Método de Pagamento')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('paid', 'Paga'), ('cancelled', 'Cancelada'), ('completed', 'Concluída')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Processado por')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tourpackage', verbose_name='Pacote')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('inquiry_type', models.CharField(choices=[('general', 'Informações Gerais'), ('booking', 'Reserva'), ('support', 'Suporte'), ('complaint', 'Reclamação'), ('suggestion', 'Sugestão')], default='general', max_length=20, verbose_name='Tipo')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('new', 'Nova'), ('in_progress', 'Em Andamento'), ('resolved', 'Resolvida'), ('closed', 'Fechada')], default='new', max_length=20, verbose_name='Status')),
                ('response', models.TextField(blank=True, verbose_name='Resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atribuído para')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tourpackage', verbose_name='Pacote Relacionado')),
            ],
            options={
                'verbose_name': 'Consulta de Cliente',
                'verbose_name_plural': 'Consultas de Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
