# Generated by Django 5.2.7 on 2025-11-01 19:25

import cadastros.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(help_text='Nome comercial do fornecedor', max_length=100)),
                ('razao_social', models.CharField(blank=True, help_text='Razão Social (se aplicável)', max_length=100)),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ no formato XX.XXX.XXX/XXXX-XX', max_length=18, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('transporte', 'Transporte'), ('hospedagem', 'Hospedagem'), ('atracao', 'Atração'), ('restaurante', 'Restaurante'), ('outro', 'Outro')], help_text='Tipo de serviço prestado', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Anotações gerais sobre o fornecedor')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='MatriculaCliente',
            fields=[
                ('id', models.CharField(default=cadastros.models.gerar_matricula_aleatoria, editable=False, help_text='Número de matrícula aleatório (6 dígitos)', max_length=6, primary_key=True, serialize=False)),
                ('cpf', models.CharField(help_text='CPF do cliente (apenas números)', max_length=11, unique=True)),
            ],
            options={
                'verbose_name': 'Matrícula Cliente',
                'verbose_name_plural': 'Matrículas Cliente',
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Ônibus Leito 46 Lugares', max_length=100, unique=True)),
                ('fileiras', models.PositiveIntegerField(default=12, help_text='Número de fileiras de assentos')),
                ('capacidade', models.PositiveIntegerField(default=48, help_text='Capacidade total de passageiros')),
                ('layout_colunas', models.CharField(default='2-2', help_text="Layout das colunas, separado por hífen (ex: '2-2', '2-1').", max_length=10)),
                ('custo_base_transporte', models.DecimalField(decimal_places=2, default=0.0, help_text='Custo estimado para o transporte deste tipo de veículo, usado se não houver cotação aceita.', max_digits=10, verbose_name='Custo Base de Transporte (R$)')),
            ],
            options={
                'verbose_name': 'Modelo de Veículo',
                'verbose_name_plural': 'Modelos de Veículos',
            },
        ),
        migrations.CreateModel(
            name='ContatoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do contato', max_length=100)),
                ('cargo', models.CharField(blank=True, help_text='Ex: Vendedor, Motorista, Gerente', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone principal do contato', max_length=128, region='BR')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações sobre este contato específico')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='cadastros.fornecedor')),
            ],
            options={
                'verbose_name': 'Contato do Fornecedor',
                'verbose_name_plural': 'Contatos do Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='ContaBancariaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(help_text='Nome ou código do banco (Ex: Itaú, 341)', max_length=100)),
                ('agencia', models.CharField(help_text='Número da agência', max_length=20)),
                ('conta', models.CharField(help_text='Número da conta com dígito', max_length=30)),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança')], default='corrente', max_length=10)),
                ('titular', models.CharField(help_text='Nome completo do titular da conta', max_length=150)),
                ('cpf_cnpj_titular', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ do Titular')),
                ('chave_pix', models.CharField(blank=True, max_length=100, verbose_name='Chave PIX')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias', to='cadastros.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do cliente', max_length=100)),
                ('cpf', models.CharField(help_text='CPF (aceita formatação: 123.456.789-00 ou 12345678900)', max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, help_text='Número do RG/CNH', max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento do cliente', null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], help_text='Gênero do cliente', max_length=10)),
                ('nacionalidade', models.CharField(default='Brasileira', help_text='Nacionalidade do cliente', max_length=50)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], help_text='Estado civil do cliente', max_length=20)),
                ('profissao', models.CharField(blank=True, help_text='Profissão do cliente', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='E-mail do cliente', max_length=254, null=True, unique=True)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Número de telefone com DDD', max_length=128, region='BR')),
                ('telefone_adicional', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Número de telefone adicional (para contato emergencial)', max_length=128, region='BR')),
                ('endereco', models.CharField(blank=True, help_text='Rua e número do endereço', max_length=200)),
                ('numero', models.CharField(blank=True, help_text='Número do imóvel', max_length=10)),
                ('complemento', models.CharField(blank=True, help_text='Complemento (apto, bloco, etc)', max_length=100)),
                ('bairro', models.CharField(blank=True, help_text='Bairro', max_length=100)),
                ('cep', models.CharField(blank=True, help_text='CEP no formato XXXXX-XXX', max_length=9, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100)),
                ('estado', models.CharField(blank=True, help_text='Estado (UF)', max_length=2, verbose_name='UF')),
                ('ponto_referencia', models.CharField(blank=True, help_text='Ponto de referência do endereço', max_length=200)),
                ('observacoes', models.TextField(blank=True, help_text='Anotações internas sobre o cliente (preferências, restrições, etc.)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('matricula', models.OneToOneField(blank=True, help_text='Número de matrícula único (gerado automaticamente)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.matriculacliente', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
