# Generated by Django 5.2.7 on 2025-11-01 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Somente Passagem, Pacote Completo', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço de venda deste pacote', max_digits=10)),
            ],
            options={
                'verbose_name': 'Pacote',
                'verbose_name_plural': 'Pacotes',
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('transporte', 'Transporte'), ('hospedagem', 'Hospedagem'), ('alimentacao', 'Alimentação'), ('guia', 'Guia Turístico'), ('seguro', 'Seguro Viagem'), ('taxas', 'Taxas/Permissões'), ('outro', 'Outro')], help_text='Tipo de serviço cotado', max_length=50)),
                ('valor_cotado', models.DecimalField(decimal_places=2, help_text='Valor proposto pelo fornecedor', max_digits=10)),
                ('data_cotacao', models.DateTimeField(auto_now_add=True, help_text='Data em que a cotação foi registrada')),
                ('observacoes', models.TextField(blank=True, help_text='Detalhes adicionais da cotação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada'), ('negociando', 'Negociando')], default='pendente', help_text='Status atual da cotação', max_length=20)),
                ('data_vencimento_pagamento', models.DateField(blank=True, help_text='Data limite para o pagamento final', null=True)),
                ('fornecedor_selecionado', models.BooleanField(default=False, help_text='Marque se esta cotação foi a escolhida para o serviço')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_recebidas', to='cadastros.fornecedor')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['-data_cotacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição do item incluído. Ex: Transporte ida e volta', max_length=200)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='passeios.pacote')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('status_pagamento', models.CharField(choices=[('aguardando', 'Aguardando Pagamento'), ('parcial', 'Pagamento Parcial'), ('pago', 'Pago Integralmente'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('status_inscricao', models.CharField(choices=[('confirmada', 'Confirmada'), ('lista_espera', 'Lista de Espera'), ('cancelada_cliente', 'Cancelada pelo Cliente'), ('cancelada_agencia', 'Cancelada pela Agência')], default='confirmada', max_length=20, verbose_name='Status da Inscrição')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações específicas sobre esta inscrição')),
                ('voucher', models.CharField(blank=True, help_text='Código único da inscrição (gerado automaticamente)', max_length=10, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='cadastros.cliente')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='passeios.pacote')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('pacote', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(blank=True, choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('transferencia', 'Transferência Bancária'), ('outro', 'Outro')], help_text='Método utilizado para o pagamento', max_length=50)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='passeios.inscricao')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='PagamentoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor pago', max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('boleto', 'Boleto'), ('outro', 'Outro')], default='transferencia', max_length=50)),
                ('observacoes', models.TextField(blank=True, help_text='Anotações ou informações do comprovante')),
                ('cotacao', models.ForeignKey(help_text='Cotação à qual este pagamento se refere', on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_fornecedor', to='passeios.cotacao')),
            ],
        ),
        migrations.CreateModel(
            name='Passeio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal do passeio', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do que o passeio inclui')),
                ('cidade_origem', models.CharField(default='A Definir', max_length=100, verbose_name='Origem')),
                ('uf_origem', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='UF')),
                ('cidade_destino', models.CharField(default='A Definir', max_length=100, verbose_name='Destino')),
                ('uf_destino', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='UF')),
                ('data_ida', models.DateTimeField(help_text='Data e hora de partida')),
                ('data_volta', models.DateTimeField(help_text='Data e hora de retorno')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='agendado', help_text='Status atual do passeio', max_length=20)),
                ('margem_lucro_desejada', models.DecimalField(decimal_places=2, default=30.0, help_text='Percentual de lucro desejado sobre o preço de venda final.', max_digits=5, verbose_name='Margem de Lucro Desejada (%)')),
                ('margem_lucro_promocional', models.DecimalField(decimal_places=2, default=10.0, help_text='Margem de lucro mínima para vendas promocionais.', max_digits=5, verbose_name='Margem de Lucro Promocional (%)')),
                ('lotacao_minima_desejada', models.PositiveIntegerField(default=0, help_text='Número mínimo de passageiros desejado para o passeio. Use 0 para desativar.', verbose_name='Lotação Mínima Desejada')),
                ('alerta_equilibrio_enviado', models.BooleanField(default=False, help_text='Marca se o e-mail de alerta de ponto de equilíbrio já foi enviado.', verbose_name='Alerta de Ponto de Equilíbrio Enviado')),
                ('fornecedor_hospedagem', models.ForeignKey(blank=True, help_text='Hotel ou pousada da hospedagem (se houver).', limit_choices_to={'tipo': 'hospedagem'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passeios_hospedagem', to='cadastros.fornecedor')),
                ('fornecedor_transporte', models.ForeignKey(help_text='Empresa de ônibus/transporte responsável.', limit_choices_to={'tipo': 'transporte'}, on_delete=django.db.models.deletion.PROTECT, related_name='passeios_transporte', to='cadastros.fornecedor')),
                ('tipo_veiculo', models.ForeignKey(blank=True, help_text='Selecione o modelo de veículo principal para este passeio.', null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipoveiculo')),
            ],
            options={
                'verbose_name': 'Passeio',
                'verbose_name_plural': 'Passeios',
            },
        ),
        migrations.AddField(
            model_name='pacote',
            name='passeio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='passeios.passeio'),
        ),
        migrations.CreateModel(
            name='GastoPasseio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição detalhada do gasto', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do gasto', max_digits=10)),
                ('data_gasto', models.DateTimeField(auto_now_add=True, help_text='Data em que o gasto foi registrado')),
                ('tipo_gasto', models.CharField(choices=[('alimentacao', 'Alimentação (Lanches, Refeições)'), ('combustivel', 'Combustível'), ('taxas', 'Taxas/Pedágios'), ('material', 'Material de Apoio'), ('imprevisto', 'Imprevisto'), ('outro', 'Outro')], help_text='Categoria do gasto', max_length=50)),
                ('responsavel', models.ForeignKey(blank=True, help_text='Usuário responsável pelo gasto', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('passeio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='passeios.passeio')),
            ],
            options={
                'verbose_name': 'Gasto do Passeio',
                'verbose_name_plural': 'Gastos do Passeio',
                'ordering': ['-data_gasto'],
            },
        ),
        migrations.AddField(
            model_name='cotacao',
            name='passeio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='passeios.passeio'),
        ),
        migrations.CreateModel(
            name='PaymentGatewayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('stripe', 'Stripe')], default='mercadopago', max_length=50)),
                ('gateway_id', models.CharField(help_text='ID único da transação no gateway', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto')], max_length=50)),
                ('parcelas', models.PositiveIntegerField(default=1)),
                ('webhook_confirmado', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('confirmada_em', models.DateTimeField(blank=True, null=True)),
                ('pagamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_transaction', to='passeios.pagamento')),
            ],
            options={
                'verbose_name': 'Transação de Gateway',
                'verbose_name_plural': 'Transações de Gateway',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='VeiculoPasseio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(help_text='Ex: Ônibus 1, Van de Apoio', max_length=100)),
                ('passeio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='passeios.passeio')),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipoveiculo')),
            ],
            options={
                'verbose_name': 'Veículo do Passeio',
                'verbose_name_plural': 'Veículos do Passeio',
            },
        ),
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assentos_reservados', to='cadastros.cliente')),
                ('veiculo_passeio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assentos', to='passeios.veiculopasseio')),
            ],
            options={
                'verbose_name': 'Assento',
                'verbose_name_plural': 'Assentos',
                'unique_together': {('veiculo_passeio', 'cliente'), ('veiculo_passeio', 'numero')},
            },
        ),
    ]
